"""initial schema

Revision ID: 7324b3100aa3
Revises:
Create Date: 2026-09-03 22:05:55.253301+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7324b3100aa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    for schema in ("auth", "entity", "evolution", "memory", "safety", "community", "research"):
        op.execute(sa.text(f'CREATE SCHEMA IF NOT EXISTS "{schema}"'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', 'RESEARCHER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True, schema='auth')
    op.create_index('ix_users_role', 'users', ['role'], unique=False, schema='auth')
    op.create_index('ix_users_username', 'users', ['username'], unique=True, schema='auth')
    op.create_table('consolidation_runs',
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('experiences_processed', sa.Integer(), nullable=False),
    sa.Column('semantic_memories_created', sa.Integer(), nullable=False),
    sa.Column('semantic_memories_updated', sa.Integer(), nullable=False),
    sa.Column('beliefs_formed', sa.Integer(), nullable=False),
    sa.Column('beliefs_updated', sa.Integer(), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='evolution'
    )
    op.create_index('ix_consolidation_generation', 'consolidation_runs', ['generation'], unique=False, schema='evolution')
    op.create_index('ix_consolidation_status', 'consolidation_runs', ['status'], unique=False, schema='evolution')
    op.create_table('evolution_events',
    sa.Column('event_type', sa.Enum('GENERATION_CREATED', 'FIRST_INTERACTION', 'FIRST_AUTONOMOUS_QUERY', 'CONSOLIDATION_CYCLE', 'GENERATION_PROMOTED', 'ARCHITECTURE_MODIFIED', 'SAFETY_EVENT', name='eventtype'), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='evolution'
    )
    op.create_index('ix_evolution_events_generation', 'evolution_events', ['generation'], unique=False, schema='evolution')
    op.create_index('ix_evolution_events_timestamp', 'evolution_events', ['created_at'], unique=False, schema='evolution')
    op.create_index('ix_evolution_events_type', 'evolution_events', ['event_type'], unique=False, schema='evolution')
    op.create_table('training_runs',
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('parent_generation', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=True),
    sa.Column('train_loss', sa.Float(), nullable=True),
    sa.Column('eval_loss', sa.Float(), nullable=True),
    sa.Column('perplexity', sa.Float(), nullable=True),
    sa.Column('tokens_processed', sa.BigInteger(), nullable=False),
    sa.Column('steps_completed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('checkpoint_path', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='evolution'
    )
    op.create_index('ix_training_generation', 'training_runs', ['generation'], unique=False, schema='evolution')
    op.create_index('ix_training_status', 'training_runs', ['status'], unique=False, schema='evolution')
    op.create_table('beliefs',
    sa.Column('proposition', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('KNOWN', 'LIKELY', 'UNCERTAIN', 'CONTRADICTED', 'UNKNOWN', name='confidencelevel'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('formed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contradiction_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index('ix_beliefs_category', 'beliefs', ['category'], unique=False, schema='memory')
    op.create_index('ix_beliefs_confidence', 'beliefs', ['confidence'], unique=False, schema='memory')
    op.create_index('ix_beliefs_generation', 'beliefs', ['generation'], unique=False, schema='memory')
    op.create_index('ix_beliefs_status', 'beliefs', ['status'], unique=False, schema='memory')
    op.create_table('episodic_memories',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('participants', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('HUMAN_CLAIM', 'WEB_SOURCE', 'DIRECT_OBSERVATION', 'INTERNAL_INFERENCE', 'PREVIOUS_BELIEF', 'CONSOLIDATED_KNOWLEDGE', name='memorysource'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('associations', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('consolidated', sa.Boolean(), nullable=False),
    sa.Column('consolidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    schema='memory'
    )
    op.create_index('ix_episodic_memories_confidence', 'episodic_memories', ['confidence'], unique=False, schema='memory')
    op.create_index('ix_episodic_memories_generation', 'episodic_memories', ['generation'], unique=False, schema='memory')
    op.create_index('ix_episodic_memories_importance', 'episodic_memories', ['importance'], unique=False, schema='memory')
    op.create_index('ix_episodic_memories_source', 'episodic_memories', ['source'], unique=False, schema='memory')
    op.create_index('ix_episodic_memories_timestamp', 'episodic_memories', ['timestamp'], unique=False, schema='memory')
    op.create_table('reflections',
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('input_memory_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('contradictions_found', sa.Integer(), nullable=False),
    sa.Column('inferences_made', sa.Integer(), nullable=False),
    sa.Column('new_memories_created', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index('ix_reflections_generation', 'reflections', ['generation'], unique=False, schema='memory')
    op.create_index('ix_reflections_trigger', 'reflections', ['trigger_type'], unique=False, schema='memory')
    op.create_table('semantic_memories',
    sa.Column('concept', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('representation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('last_reinforced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index('ix_semantic_memories_category', 'semantic_memories', ['category'], unique=False, schema='memory')
    op.create_index('ix_semantic_memories_confidence', 'semantic_memories', ['confidence'], unique=False, schema='memory')
    op.create_index('ix_semantic_memories_generation', 'semantic_memories', ['generation'], unique=False, schema='memory')
    op.create_table('web_queries',
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('search_time_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index('ix_web_queries_generation', 'web_queries', ['generation'], unique=False, schema='memory')
    op.create_index('ix_web_queries_timestamp', 'web_queries', ['created_at'], unique=False, schema='memory')
    op.create_index('ix_web_queries_trigger', 'web_queries', ['trigger_type'], unique=False, schema='memory')
    op.create_table('audit_logs',
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False, schema='safety')
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False, schema='safety')
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['created_at'], unique=False, schema='safety')
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='auth'
    )
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=True, schema='auth')
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False, schema='auth')
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('ix_sessions_expires', 'sessions', ['expires_at'], unique=False, schema='auth')
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False, schema='auth')
    op.create_table('consents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'consent_type', name='uq_user_consent'),
    schema='community'
    )
    op.create_index('ix_consents_type', 'consents', ['consent_type'], unique=False, schema='community')
    op.create_index('ix_consents_user_id', 'consents', ['user_id'], unique=False, schema='community')
    op.create_table('contributions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contribution_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='community'
    )
    op.create_index('ix_contributions_status', 'contributions', ['status'], unique=False, schema='community')
    op.create_index('ix_contributions_type', 'contributions', ['contribution_type'], unique=False, schema='community')
    op.create_index('ix_contributions_user_id', 'contributions', ['user_id'], unique=False, schema='community')
    op.create_table('reports',
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='community'
    )
    op.create_index('ix_reports_reporter', 'reports', ['reporter_id'], unique=False, schema='community')
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False, schema='community')
    op.create_index('ix_reports_target', 'reports', ['target_type', 'target_id'], unique=False, schema='community')
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('state', sa.Enum('INTERACTION', 'REFLECTION', 'RESEARCH', 'CONSOLIDATION', 'TRAINING', 'EVALUATION', 'IDLE', name='operationalstate'), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='entity'
    )
    op.create_index('ix_conversations_generation', 'conversations', ['generation'], unique=False, schema='entity')
    op.create_index('ix_conversations_state', 'conversations', ['state'], unique=False, schema='entity')
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False, schema='entity')
    op.create_table('model_generations',
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('parent_generation', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'TRAINING', 'EVALUATING', 'PROMOTED', 'REJECTED', 'ARCHIVED', name='generationstatus'), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('tokenizer_path', sa.String(length=500), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('training_run_id', sa.UUID(), nullable=True),
    sa.Column('eval_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('architecture_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['evolution.training_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_number'),
    schema='evolution'
    )
    op.create_index('ix_generations_number', 'model_generations', ['generation_number'], unique=True, schema='evolution')
    op.create_index('ix_generations_parent', 'model_generations', ['parent_generation'], unique=False, schema='evolution')
    op.create_index('ix_generations_status', 'model_generations', ['status'], unique=False, schema='evolution')
    op.create_table('belief_evidence',
    sa.Column('belief_id', sa.UUID(), nullable=False),
    sa.Column('episodic_memory_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('HUMAN_CLAIM', 'WEB_SOURCE', 'DIRECT_OBSERVATION', 'INTERNAL_INFERENCE', 'PREVIOUS_BELIEF', 'CONSOLIDATED_KNOWLEDGE', name='memorysource'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('supports', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['belief_id'], ['memory.beliefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episodic_memory_id'], ['memory.episodic_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index('ix_belief_evidence_belief_id', 'belief_evidence', ['belief_id'], unique=False, schema='memory')
    op.create_index('ix_belief_evidence_episodic_id', 'belief_evidence', ['episodic_memory_id'], unique=False, schema='memory')
    op.create_index('ix_belief_evidence_source', 'belief_evidence', ['source'], unique=False, schema='memory')
    op.create_table('semantic_memory_links',
    sa.Column('semantic_memory_id', sa.UUID(), nullable=False),
    sa.Column('episodic_memory_id', sa.UUID(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['episodic_memory_id'], ['memory.episodic_memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semantic_memory_id'], ['memory.semantic_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_memory_id', 'episodic_memory_id', name='uq_semantic_episodic_link'),
    schema='memory'
    )
    op.create_index('ix_semantic_links_episodic_id', 'semantic_memory_links', ['episodic_memory_id'], unique=False, schema='memory')
    op.create_index('ix_semantic_links_semantic_id', 'semantic_memory_links', ['semantic_memory_id'], unique=False, schema='memory')
    op.create_table('web_sources',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('credibility', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['memory.web_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index('ix_web_sources_credibility', 'web_sources', ['credibility'], unique=False, schema='memory')
    op.create_index('ix_web_sources_domain', 'web_sources', ['domain'], unique=False, schema='memory')
    op.create_index('ix_web_sources_query_id', 'web_sources', ['query_id'], unique=False, schema='memory')
    op.create_index('ix_web_sources_url', 'web_sources', ['url'], unique=False, schema='memory')
    op.create_table('system_events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_index('ix_system_events_severity', 'system_events', ['severity'], unique=False, schema='safety')
    op.create_index('ix_system_events_timestamp', 'system_events', ['created_at'], unique=False, schema='safety')
    op.create_index('ix_system_events_type', 'system_events', ['event_type'], unique=False, schema='safety')
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ENTITY', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('memories_retrieved', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('web_sources_used', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['entity.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='entity'
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False, schema='entity')
    op.create_index('ix_messages_generation', 'messages', ['generation'], unique=False, schema='entity')
    op.create_index('ix_messages_role', 'messages', ['role'], unique=False, schema='entity')
    op.create_table('source_citations',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('episodic_memory_id', sa.UUID(), nullable=True),
    sa.Column('belief_id', sa.UUID(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['belief_id'], ['memory.beliefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episodic_memory_id'], ['memory.episodic_memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['memory.web_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='memory'
    )
    op.create_index('ix_citations_belief_id', 'source_citations', ['belief_id'], unique=False, schema='memory')
    op.create_index('ix_citations_episodic_id', 'source_citations', ['episodic_memory_id'], unique=False, schema='memory')
    op.create_index('ix_citations_source_id', 'source_citations', ['source_id'], unique=False, schema='memory')
    op.create_table('safety_violations',
    sa.Column('violation_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['entity.conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='safety'
    )
    op.create_index('ix_safety_violations_resolved', 'safety_violations', ['resolved'], unique=False, schema='safety')
    op.create_index('ix_safety_violations_severity', 'safety_violations', ['severity'], unique=False, schema='safety')
    op.create_index('ix_safety_violations_type', 'safety_violations', ['violation_type'], unique=False, schema='safety')
    op.create_index('ix_safety_violations_user_id', 'safety_violations', ['user_id'], unique=False, schema='safety')
    op.create_table('feedback',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Enum('USEFUL', 'INCORRECT', 'QUESTIONABLE', 'GOOD_INTERPRETATION', 'FACTUAL_CORRECTION', 'SAFETY_ISSUE', 'OTHER', name='feedbacktype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['entity.messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='community'
    )
    op.create_index('ix_feedback_generation', 'feedback', ['generation'], unique=False, schema='community')
    op.create_index('ix_feedback_message_id', 'feedback', ['message_id'], unique=False, schema='community')
    op.create_index('ix_feedback_type', 'feedback', ['feedback_type'], unique=False, schema='community')
    op.create_index('ix_feedback_user_id', 'feedback', ['user_id'], unique=False, schema='community')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_user_id', table_name='feedback', schema='community')
    op.drop_index('ix_feedback_type', table_name='feedback', schema='community')
    op.drop_index('ix_feedback_message_id', table_name='feedback', schema='community')
    op.drop_index('ix_feedback_generation', table_name='feedback', schema='community')
    op.drop_table('feedback', schema='community')
    op.drop_index('ix_safety_violations_user_id', table_name='safety_violations', schema='safety')
    op.drop_index('ix_safety_violations_type', table_name='safety_violations', schema='safety')
    op.drop_index('ix_safety_violations_severity', table_name='safety_violations', schema='safety')
    op.drop_index('ix_safety_violations_resolved', table_name='safety_violations', schema='safety')
    op.drop_table('safety_violations', schema='safety')
    op.drop_index('ix_citations_source_id', table_name='source_citations', schema='memory')
    op.drop_index('ix_citations_episodic_id', table_name='source_citations', schema='memory')
    op.drop_index('ix_citations_belief_id', table_name='source_citations', schema='memory')
    op.drop_table('source_citations', schema='memory')
    op.drop_index('ix_messages_role', table_name='messages', schema='entity')
    op.drop_index('ix_messages_generation', table_name='messages', schema='entity')
    op.drop_index('ix_messages_conversation_id', table_name='messages', schema='entity')
    op.drop_table('messages', schema='entity')
    op.drop_index('ix_system_events_type', table_name='system_events', schema='safety')
    op.drop_index('ix_system_events_timestamp', table_name='system_events', schema='safety')
    op.drop_index('ix_system_events_severity', table_name='system_events', schema='safety')
    op.drop_table('system_events', schema='safety')
    op.drop_index('ix_web_sources_url', table_name='web_sources', schema='memory')
    op.drop_index('ix_web_sources_query_id', table_name='web_sources', schema='memory')
    op.drop_index('ix_web_sources_domain', table_name='web_sources', schema='memory')
    op.drop_index('ix_web_sources_credibility', table_name='web_sources', schema='memory')
    op.drop_table('web_sources', schema='memory')
    op.drop_index('ix_semantic_links_semantic_id', table_name='semantic_memory_links', schema='memory')
    op.drop_index('ix_semantic_links_episodic_id', table_name='semantic_memory_links', schema='memory')
    op.drop_table('semantic_memory_links', schema='memory')
    op.drop_index('ix_belief_evidence_source', table_name='belief_evidence', schema='memory')
    op.drop_index('ix_belief_evidence_episodic_id', table_name='belief_evidence', schema='memory')
    op.drop_index('ix_belief_evidence_belief_id', table_name='belief_evidence', schema='memory')
    op.drop_table('belief_evidence', schema='memory')
    op.drop_index('ix_generations_status', table_name='model_generations', schema='evolution')
    op.drop_index('ix_generations_parent', table_name='model_generations', schema='evolution')
    op.drop_index('ix_generations_number', table_name='model_generations', schema='evolution')
    op.drop_table('model_generations', schema='evolution')
    op.drop_index('ix_conversations_user_id', table_name='conversations', schema='entity')
    op.drop_index('ix_conversations_state', table_name='conversations', schema='entity')
    op.drop_index('ix_conversations_generation', table_name='conversations', schema='entity')
    op.drop_table('conversations', schema='entity')
    op.drop_index('ix_reports_target', table_name='reports', schema='community')
    op.drop_index('ix_reports_status', table_name='reports', schema='community')
    op.drop_index('ix_reports_reporter', table_name='reports', schema='community')
    op.drop_table('reports', schema='community')
    op.drop_index('ix_contributions_user_id', table_name='contributions', schema='community')
    op.drop_index('ix_contributions_type', table_name='contributions', schema='community')
    op.drop_index('ix_contributions_status', table_name='contributions', schema='community')
    op.drop_table('contributions', schema='community')
    op.drop_index('ix_consents_user_id', table_name='consents', schema='community')
    op.drop_index('ix_consents_type', table_name='consents', schema='community')
    op.drop_table('consents', schema='community')
    op.drop_index('ix_sessions_user_id', table_name='sessions', schema='auth')
    op.drop_index('ix_sessions_expires', table_name='sessions', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.drop_index('ix_api_keys_user_id', table_name='api_keys', schema='auth')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys', schema='auth')
    op.drop_table('api_keys', schema='auth')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs', schema='safety')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs', schema='safety')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs', schema='safety')
    op.drop_table('audit_logs', schema='safety')
    op.drop_index('ix_web_queries_trigger', table_name='web_queries', schema='memory')
    op.drop_index('ix_web_queries_timestamp', table_name='web_queries', schema='memory')
    op.drop_index('ix_web_queries_generation', table_name='web_queries', schema='memory')
    op.drop_table('web_queries', schema='memory')
    op.drop_index('ix_semantic_memories_generation', table_name='semantic_memories', schema='memory')
    op.drop_index('ix_semantic_memories_confidence', table_name='semantic_memories', schema='memory')
    op.drop_index('ix_semantic_memories_category', table_name='semantic_memories', schema='memory')
    op.drop_table('semantic_memories', schema='memory')
    op.drop_index('ix_reflections_trigger', table_name='reflections', schema='memory')
    op.drop_index('ix_reflections_generation', table_name='reflections', schema='memory')
    op.drop_table('reflections', schema='memory')
    op.drop_index('ix_episodic_memories_timestamp', table_name='episodic_memories', schema='memory')
    op.drop_index('ix_episodic_memories_source', table_name='episodic_memories', schema='memory')
    op.drop_index('ix_episodic_memories_importance', table_name='episodic_memories', schema='memory')
    op.drop_index('ix_episodic_memories_generation', table_name='episodic_memories', schema='memory')
    op.drop_index('ix_episodic_memories_confidence', table_name='episodic_memories', schema='memory')
    op.drop_table('episodic_memories', schema='memory')
    op.drop_index('ix_beliefs_status', table_name='beliefs', schema='memory')
    op.drop_index('ix_beliefs_generation', table_name='beliefs', schema='memory')
    op.drop_index('ix_beliefs_confidence', table_name='beliefs', schema='memory')
    op.drop_index('ix_beliefs_category', table_name='beliefs', schema='memory')
    op.drop_table('beliefs', schema='memory')
    op.drop_index('ix_training_status', table_name='training_runs', schema='evolution')
    op.drop_index('ix_training_generation', table_name='training_runs', schema='evolution')
    op.drop_table('training_runs', schema='evolution')
    op.drop_index('ix_evolution_events_type', table_name='evolution_events', schema='evolution')
    op.drop_index('ix_evolution_events_timestamp', table_name='evolution_events', schema='evolution')
    op.drop_index('ix_evolution_events_generation', table_name='evolution_events', schema='evolution')
    op.drop_table('evolution_events', schema='evolution')
    op.drop_index('ix_consolidation_status', table_name='consolidation_runs', schema='evolution')
    op.drop_index('ix_consolidation_generation', table_name='consolidation_runs', schema='evolution')
    op.drop_table('consolidation_runs', schema='evolution')
    op.drop_index('ix_users_username', table_name='users', schema='auth')
    op.drop_index('ix_users_role', table_name='users', schema='auth')
    op.drop_index('ix_users_email', table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
